### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by dave14305**
The previous package list commit for python breaks building. Revert the install list to the last known working package list that worked correctly (tested on Ubuntu 20.04 for rt-ac86u build).

### CODE REVIEW

**Comment by kernol51** [comment]
agreed @dave14305 - really thought we were out of the woods.
did a fully clean build of VM with Ub 20.04.5 and clean amcfwm install - then tried build RT-AX86U - got all the way to the end ... but failed to makefile :-(

**Comment by kernol51** [comment]
I got compiles to work again on top of amcfwm 1.1.4 simply by installing libpython2.7:i386 and automake-1.15 [no idea why other than maybe it plugs a gap in 1.16?] AND installing python-is-python**3**
However - that compiles AC models - something is broken on the Master for compiling AX models - my RT-AX86U failed while two AC models succeeded in the same run.

**Comment by dave14305** [comment]
> something is broken on the Master for compiling AX models - my RT-AX86U failed while two AC models succeeded in the same run.

It looks like @RMerl’s recent commit to add `libcap-ng` is failing builds at the moment. The perils of master…

**Comment by RMerl** [comment]
libcap-ng is necessary for OpenVPN 2.6.  It`s used now to handle user privilege drops.

RT-AX86U_Pro and GT-AXE16000 compiled fine for me in my recent development work.

**Comment by RMerl** [comment]
The issue with libcap-ng is not with AX models, it's with kernel version < 4.3.

**Comment by dave14305** [comment]
> may be worth noting for 1st time installers that base install of Ubuntu 20.04.5 does not include curl - so must install that before trying to run install command for amcfwm.

Or use wget. #15

**Comment by kernol51** [comment]
> > something is broken on the Master for compiling AX models - my RT-AX86U failed while two AC models succeeded in the same run.
> 
> It looks like @RMerl’s recent commit to add `libcap-ng` is failing builds at the moment. The perils of master…

In Eric's Build-All script he is pointing certain router models to specific branches - [ for eg 386.x for AC's ].  Not sure if @Adamm00 script is pulling that through?  Noted that the Changelog file for AC86U compiled with amcfwm contains reference to fw version 388.?  which of course it should not.

**Comment by dave14305** [comment]
> In Eric's Build-All script he is pointing certain router models to specific branches - [ for eg 386.x for AC's ]. Not sure if @Adamm00 script is pulling that through?
Of course it is, that was the original point of my contributions.
> Noted that the Changelog file for AC86U compiled with amcfwm contains reference to fw version 388.? which of course it should not.
The CHANGELOG is copied from master before the branching is done. That can be fixed later.

**Comment by dave14305** [comment]
An rt-ax86u build was successful after Merlin’s latest fix today. rt-ax86u_pro is building now.

**Comment by kernol51** [comment]
> An rt-ax86u build was successful after Merlin’s latest fix today. rt-ax86u_pro is building now.

oh yeah ... "it wasn't me" - Shaggy ... :-) ...

**Comment by dave14305** [comment]
> My RT-AX86U_Pro build failed .... :-(

Mine failed also. 
```
USERSPACE ENDED
make -C /home/ubuntu/amng.ax86pro/release/src-rt-5.04axhnd.675x/bootloaders/armtf KERNEL_ARCH=aarch64 BRCM_CHIP=4912
make[3]: Entering directory '/home/ubuntu/amng.ax86pro/release/src-rt-5.04axhnd.675x/bootloaders/armtf'
Untarring source and overrides...
Removing .git folder...
Applying patches to ARM_TF...
Link platform bcm
make[4]: Entering directory '/home/ubuntu/amng.ax86pro/release/src-rt-5.04axhnd.675x/bootloaders/armtf/arm-trusted-firmware-2.2'
  CC      lib/libfdt/fdt.c
cc1: error: /home/ubuntu/amng.ax86pro/release/src-rt-5.04axhnd.675x/userspace/private/libs/wlcsm/include: No such file or directory [-Werror=missing-include-dirs]
cc1: all warnings being treated as errors
make[4]: *** [lib/libfdt/libfdt.mk:20: build/bcm/debug/libfdt/fdt.o] Error 1
make[4]: Leaving directory '/home/ubuntu/amng.ax86pro/release/src-rt-5.04axhnd.675x/bootloaders/armtf/arm-trusted-firmware-2.2'
make[3]: *** [Makefile:69: armtf] Error 2
make[3]: Leaving directory '/home/ubuntu/amng.ax86pro/release/src-rt-5.04axhnd.675x/bootloaders/armtf'
make[2]: *** [build/Makefile:206: atf] Error 2
make[2]: Leaving directory '/home/ubuntu/amng.ax86pro/release/src-rt-5.04axhnd.675x'
make[1]: *** [Makefile:5848: bin] Error 2
make[1]: Leaving directory '/home/ubuntu/amng.ax86pro/release/src-rt-5.04axhnd.675x'
make: *** [Makefile:6053: rt-ax86u_pro] Error 2
```

**Comment by kernol51** [comment]
yep - precisely the same spot where mine failed.  Problem is with Master once again.

My RT-AX86U compiled properly [as did yours].

**Comment by kernol51** [comment]
@Adamm00 - may be worthwhile mentioning on your base GitHub page for this script that after updating - must run the install command?  As things stand an updated script will not enable compiles without at least running the extra required packages?

**Comment by dave14305** [comment]
My AX86U_pro build seemed to run ok after creating the missing directory:
```
mkdir -p $HOME/amng.ax86pro/release/src-rt-5.04axhnd.675x/userspace/private/libs/wlcsm/include 
```

**Comment by kernol51** [comment]
> 
MANY thanks @dave14305 - you've been a champ in sorting the code here ... just wish I could provide you with jugs of coffee or cases of beer.  There is still work that can be done [if you feel inclined] - but we are functional again and that's the most important.  Cheers John

**Pull request merged**
